name: "scheduled-web"
on:
  # allow manually triggering
  workflow_dispatch:

  # run this every night to make sure nothing breaks
  schedule:
    - cron: "0 0 * * *"

  # run on push to any branch
  push:

# cancel the job if a newer pipeline starts for the same MR or branch
concurrency:
  group: scheduled-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: pnpm build
    