name: "scheduled"
on:
  # allow manually triggering
  workflow_dispatch:

  # run this every night to make sure nothing breaks
  schedule:
    - cron: "0 0 * * *"

  # run on push to any branch
  push:

# cancel the job if a newer pipeline starts for the same MR or branch
concurrency:
  group: scheduled-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_BIN="$HOME/.bun/bin"
          echo "$BUN_BIN" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Check TypeScript builds
        run: bun tsc --noEmit # ensures the code compiles without generating .js file.

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun eslint . --max-warnings=0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test